# Generated by Django 4.2.4 on 2023-08-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_assignment_job_assignment_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='hr.employee'),
        ),
    ]
